from fastapi import APIRouter, Depends, UploadFile, File, HTTPException
from sqlalchemy.orm import Session
import logging

from database import get_db
import models, schemas
from utils.security import get_current_recruiter
from services import recruiter_service
from services.resume_service import get_resume_preview
from utils.cache import get_cached_preview

logger = logging.getLogger(__name__)
router = APIRouter(prefix="/recruiter", tags=["Recruiter"])


@router.get("/profile", response_model=schemas.RecruiterProfileResponse)
def get_profile(
    db: Session = Depends(get_db),
    current_user: models.User = Depends(get_current_recruiter)
):
    """Returns the hiring profile, or an empty one for a brand new recruiter.

    An empty profile (no company/industry, `onboarding_completed: false`) is the
    signal the frontend uses to open the onboarding wizard.
    """
    # Must go through `serialize_profile` — the raw row holds TEXT/JSON columns
    # that the response model cannot validate directly.
    return recruiter_service.serialize_profile(
        recruiter_service.get_or_create_profile(db, current_user)
    )


@router.put("/profile", response_model=schemas.RecruiterProfileResponse)
def update_profile(
    payload: schemas.RecruiterProfileUpdate,
    db: Session = Depends(get_db),
    current_user: models.User = Depends(get_current_recruiter)
):
    """Option A — save the manual onboarding form."""
    return recruiter_service.update_profile(db, current_user, payload)


@router.post("/profile/parse-bio")
async def parse_bio(
    file: UploadFile = File(...),
    db: Session = Depends(get_db),
    current_user: models.User = Depends(get_current_recruiter)
):
    """Option B — parse an uploaded recruiter bio/resume PDF with Gemini and
    apply the extracted fields to the profile. Re-uploading re-verifies them."""
    return await recruiter_service.parse_recruiter_bio_upload(db, current_user, file)


@router.post("/actions", response_model=schemas.CandidateActionResponse)
def record_action(
    payload: schemas.CandidateActionCreate,
    db: Session = Depends(get_db),
    current_user: models.User = Depends(get_current_recruiter)
):
    """Persist a shortlist / reject / interview / offer decision."""
    return recruiter_service.record_action(db, current_user, payload)


@router.get("/actions", response_model=list[schemas.CandidateActionResponse])
def list_actions(
    db: Session = Depends(get_db),
    current_user: models.User = Depends(get_current_recruiter)
):
    return recruiter_service.list_actions(db, current_user)


@router.get("/metrics")
def get_metrics(
    db: Session = Depends(get_db),
    current_user: models.User = Depends(get_current_recruiter)
):
    """Real dashboard metrics. All zero for a newly registered account."""
    return recruiter_service.get_recruiter_metrics(db, current_user)


@router.get("/candidates/{candidate_id}/intelligence", response_model=schemas.CandidateIntelligence)
async def get_candidate_intelligence(
    candidate_id: int,
    db: Session = Depends(get_db),
    current_user: models.User = Depends(get_current_recruiter)
):
    """The complete AI-parsed dataset for one candidate, for the spotlight /
    profile view.

    The AI resume preview is normally generated by its owner. If it has never
    been generated we generate it here on first access (and cache it), so the
    recruiter view is not stuck with a half-empty profile card.
    """
    candidate = db.query(models.User).filter(models.User.id == candidate_id).first()
    if not candidate:
        raise HTTPException(status_code=404, detail="Candidate not found")

    resume = (
        db.query(models.Resume)
        .filter(models.Resume.owner_id == candidate.id)
        .order_by(models.Resume.created_at.desc())
        .first()
    )
    if resume and not get_cached_preview(resume.id):
        try:
            await get_resume_preview(resume.id, db, candidate.id)
        except Exception as e:
            # A preview failure must not fail the whole request — the ATS half
            # of the payload is still worth returning.
            logger.warning(f"Preview generation failed for candidate {candidate_id}: {str(e)}")

    return recruiter_service.get_candidate_intelligence(db, candidate)
